Fs=4000;
channels =1;
bits=16;
r=audiorecorder(Fs,bits,channels);
duration=5;
disp("Recording Started");
recordblocking(r,duration);
disp('Recording Stopped');
x=getaudiodata(r);
t=0:1/Fs:(length(x)-1)/Fs;
subplot(211);
plot(t,x,'LineWidth',1.5);
xlabel("time(sec)");
ylabel('amplitude');
title("time domain plot of the recorded signal");
n=length(x);
F=0:(n-1)*Fs/n;
Y=fft(x,n);
F_0=(-n/2:n/2-1).*(Fs/n);
Y_0=fftshift(Y);
AY_0=abs(Y_0);
subplot(212);
plot(F_0, AY_0,'LineWidth',1.5);
xlabel("frequency(Hz)");
ylabel('amplitude');
title("frequency domain plot of the audio signal");
filename="myvoice.wav";
audiowrite(filename,x,Fs);
%sound(x,Fs,bits); call this function in the command window after running the code.
